### ISSUE TITLE
'Paste' button disappears in starting screen after pushing the 'forget' button

### ISSUE THREAD

**Issue by serrq** [you-apps/TranslateYou#435]
### Describe your suggested feature

When the clipboard is filled I want paste the clipboard content into the text field in TY without have to evoke the system copy/paste.

If the clipboard is empty, then show a toastbar message like "clipboard is empty" and do nothing.

### Other details

![1000113568](https://github.com/you-apps/TranslateYou/assets/113377431/4373bf40-8aec-41ca-b1b1-396b8d39f346)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> But if you fill again the clipboard, 'paste' button doesn't appear. The point is this. So, why it disappear? Cannot it staying there?
>
We can only listen for clipboard changes while the app is focused, so if you're copying something in an other app while Translate You is in the background, Translate You won't notice it.

If it'd stay there all the time, I'd consider that user unfriendly and annoying because it probably won't be useful most times as the clipboard is empty.

**Comment by drogga** [comment]
@Bnyro On A.8.1 x86 the "Forget" button produces the following crash with v.10.0, no such problem in v.9.0, I suspect it's whatever you did in this commit dbcff4d946350b0a8010e224bc157ce052629eda:

FATAL EXCEPTION: main
Process: com.bnyro.translate, PID: 16702
java.lang.NullPointerException: Attempt to read from field 'android.content.ClipDescription android.content.ClipData.mClipDescription' on a null object reference
	at android.content.ClipData.<init>(ClipData.java:728)
	at w.q.a(SourceFile:3)
	at w.q.c(SourceFile:25)
	at o.x.l(SourceFile:403)
	at t.s2.invokeSuspend(SourceFile:134)
	at i6.a.resumeWith(Unknown Source:8)
	at d6.n.k2(Unknown Source:80)
	at y6.h.p(SourceFile:138)
	at y6.h.B(SourceFile:45)
	at y6.h.resumeWith(SourceFile:17)
	at m1.j0.y0(SourceFile:51)
	at m1.j0.k0(SourceFile:31)
	at s.f.k0(Unknown Source:4)
	at s.d.k0(Unknown Source:4)
	at m1.j.f(SourceFile:167)
	at m1.j.f(SourceFile:146)
	at m1.j.f(SourceFile:146)
	at m1.j.f(SourceFile:146)
	at m1.j.f(SourceFile:146)
	at m1.j.f(SourceFile:146)
	at m1.f.b(SourceFile:30)
	at m1.x.a(SourceFile:122)
	at s1.v.D(SourceFile:79)
	at s1.v.l(SourceFile:224)
	at s1.v.dispatchTouchEvent(SourceFile:83)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3317)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
	at android.view.View.dispatchPointerEvent(View.java:12015)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:463)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
